export const FOODS = {
  south_indian_veg: [
    'Idli with Sambar',
    'Dosa with Chutney',
    'Uttapam',
    'Pongal',
    'Vegetable Korma',
    'Avial',
    'Rasam Rice',
    'Curd Rice',
    'Bisi Bele Bath',
    'Adai',
  ],
  south_indian_non_veg: [
    'Chicken Chettinad',
    'Fish Curry',
    'Prawn Fry',
    'Mutton Biryani',
    'Chicken 65',
    'Egg Curry',
  ],
  common_veg: [
    'Roti with Dal Tadka',
    'Paneer Butter Masala',
    'Aloo Gobi',
    'Chole (Chickpea Curry)',
    'Palak Paneer',
    'Mixed Vegetable Sabzi',
    'Rajma (Kidney Bean Curry)',
    'Lentil Soup',
    'Quinoa Salad',
    'Oatmeal with fruits',
    'Brown Rice with steamed vegetables',
  ],
  common_non_veg: [
    'Grilled Chicken Breast',
    'Scrambled Eggs',
    'Boiled Eggs',
    'Chicken Curry',
    'Fish Tikka',
    'Tandoori Chicken',
    'Omelette',
    'Salmon Salad',
  ],
  fruits: [
    'Apple',
    'Banana',
    'Orange',
    'Grapes',
    'Mango',
    'Pineapple',
    'Watermelon'
  ],
  snacks: [
    'Handful of Almonds',
    'Greek Yogurt',
    'Sprouts Salad',
    'Fruit Salad',
    'Roasted Chickpeas',
  ]
};
